---
title: "mp4"
output:
  html_document:
    code_folding: hide
---

```{r}
library(mdsr)
library(RMySQL)
library(ggplot2)
library(knitr)
```

```{r, include=FALSE}
library(tidyverse)
library(RMySQL)
library(DBI)
library(dbplyr)
db <- dbConnect(MySQL(), 
                host = "scidb.smith.edu", 
                user = "mth292", 
                password = "RememberPi", 
                dbname = "imdb")
knitr::opts_chunk$set(connection = db, max.print = 20)
```


```{r}
#Gets info on sequels, remakes, and spinoffs
#Uses indexes on type_ids

sequel_info <- db %>%
  dbGetQuery("SELECT ml.movie_id, t.title, mi.info AS original_runtime, ml.linked_movie_id AS sequel_id, t2.title AS sequel_title, mi2.info AS sequel_runtime, ml.link_type_id, t.production_year AS original_year, t2.production_year AS sequel_year
FROM movie_link ml
JOIN title t ON t.id = ml.movie_id
JOIN title t2 ON t2.id = linked_movie_id
JOIN movie_info mi ON mi.movie_id = ml.movie_id
JOIN movie_info mi2 ON mi2.movie_id = ml.linked_movie_id
WHERE ml.link_type_id IN (2, 4, 12)
  AND t.kind_id = 1
  AND mi.info_type_id = 1 
  AND mi2.info_type_id = 1
  AND mi.info > 89
  AND mi2.info > 89;
")
```

```{r}
all_movies <- db %>%
  dbGetQuery("SELECT t.id AS movie_id, t.title, mi.info AS original_runtime, t.production_year AS original_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE t.kind_id = 1
  AND mi.info_type_id = 1 
  AND mi.info > 89
")
```

```{r}
#gets gross of movies (max cumulative gross in USA only, due to constraints w/ format of data)
gross <- db %>% 
  dbGetQuery('SELECT mi.movie_id, mi.info AS gross
             FROM movie_info mi
             WHERE mi.info_type_id = 107;
             ') %>% 
  filter(grepl('\\$', gross)) %>% 
  filter(grepl('\\(USA)', gross)) %>% 
  mutate(gross = gsub('\\s.*', '', gross)) %>%
  mutate(gross = gsub('\\D', '', gross)) %>%
  mutate(gross = as.numeric(gross)) %>%
  group_by(movie_id) %>% 
  summarize(max_gross = max(gross)) %>% 
  arrange(desc(max_gross))
```

```{r}
#filters for duplicates (so only original movie shows up, w/ sequels linking to it)
#adds decade column
sequel_info <- sequel_info %>% 
  filter(!(title %in% sequel_title)) %>% 
  mutate(decade = 10 * floor(original_year / 10)) %>% 
  select(movie_id, title, original_year, decade, sequel_title, sequel_year, link_type_id) %>%
  left_join(gross, movie_id = movie_id) %>% 
  unique()
all_movies <- all_movies %>% 
  mutate(decade = 10 * floor(original_year / 10)) %>% 
  left_join(gross, movie_id = movie_id) %>% 
  unique()

#Function that finds top 10 grossing movies
top10 <- function(data) {
  data %>%
    group_by(title) %>%
    summarize(top_movies = max(max_gross)) %>%
    arrange(desc(top_movies)) %>%
    head(10)
}

#Finds top 10 grossing movies per decade
top_sequels_decade <- sequel_info %>% 
  filter(!is.na(max_gross)) %>% 
  group_by(decade) %>%
  do(top10(.))
  
```

```{r}
#Calculates popular sequels
pop_seq <- sequel_info %>% 
  filter(title %in% top_sequels_decade$title & !is.na(max_gross)) %>% 
  select(decade, title, original_year, sequel_title, sequel_year, link_type_id) %>% 
  mutate(title = reorder(title, original_year)) %>% 
  mutate(link_type_id = factor(link_type_id))
```

```{r}
pop_seq2 <- pop_seq %>%
  filter(original_year >= 2000)
```


```{r}
ggplot(pop_seq2, aes(x = original_year, y = title)) +
  geom_segment(aes(xend = sequel_year, yend = title), size = 2) +
  geom_point(size = 3) +
  geom_point(aes(x = sequel_year, y = title, color = link_type_id), size = 3) +
  labs(color = 'Type of Movie', title = "Sequels/Remakes/Spinoffs Produced by Decade", x = "Release Year of Original Movie", y = "Movie Title", caption = "(Based on data from IMDb) Each panel includes the top ten grossing movie of that decade.") +
  theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 11),
        plot.title = element_text(size = 28),
        plot.caption = element_text(size = 12.5),
        strip.text.x = element_text(size = 14),
        legend.title = element_text(size = 16),
        legend.text = element_text(size = 14),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20)) +
  scale_color_discrete(labels = c('Sequel', 'Remake')) +
  scale_y_discrete(labels = scales::wrap_format(40)) +
  scale_x_continuous(limits = c(2000, 2020), expand = c(0, 0)) +
  facet_wrap( ~ decade, nrow = 5, scales = "free_y") 
```
